using Solid.Examples.NetEscapades.EnumGenerators.Models;
using Solid.Templates;
using static Solid.Templates.Controls.Fluent;

namespace Solid.Examples.NetEscapades.EnumGenerators;

/// <summary>
///     Demonstrates how <c>Solid.Templates</c> could have been used in <c>NetEscapades.EnumGenerators</c>.
///     <para/>
///     The example below tries to replicate the behavior of
///     <a href="https://github.com/andrewlock/NetEscapades.EnumGenerators/blob/d3995b8fa8854357c902e2d2b4495ed16c5f8546/src/NetEscapades.EnumGenerators.Generators/SourceGenerationHelper.cs#L8-L235">
///     <c>SourceGenerationHelper</c>
///     </a>
///     (lines 8-235 as of commit
///     <a href="https://github.com/andrewlock/NetEscapades.EnumGenerators/commit/d3995b8fa8854357c902e2d2b4495ed16c5f8546">
///     <c>d3995b8</c>
///     </a>).
/// </summary>
internal static class EnumGenerator
{
    public static Code Generate(EnumDefinition @enum)
    {
        var code = new Code();

        code.Append(
            // lang=c#
            $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the NetEscapades.EnumGenerators source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable

            {{If(@enum.Namespace is not null)}}
            namespace {{@enum.Namespace}}
            {
                {{Body(@enum)}}
            }
            {{Else}}
            {{Body(@enum)}}
            {{End}}
            """);

        return code;
    }

    private static Action<Code> Body(EnumDefinition @enum)
    {
        return code => code.Append(
            // lang=c#
            $$"""
              #pragma warning disable CS0612 // Ignore usages of obsolete members or enums
              #pragma warning disable CS0618 // Ignore usages of obsolete members or enums

              /// <summary>
              /// Extension methods for <see cref="{{@enum.GlobalFullyQualifiedName}}"/>
              /// </summary>
              [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NetEscapades.EnumGenerators", "{{Constants.Version}}")]
              {{@enum.Accessibility}} static partial class {{@enum.Name}}
              {
                  /// <summary>
                  /// The number of members in the enum.
                  /// This is a non-distinct count of defined names.
                  /// </summary>
                  public const int Length = {{@enum.Members.Count}};

                  /// <summary>
                  /// Returns the string representation of the <see cref="{{@enum.GlobalFullyQualifiedName}}"/> value.
                  /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                  /// </summary>
                  /// <param name="value">The value to retrieve the string value for</param>
                  /// <returns>The string representation of the value, the same as that returned by <c>ToString()</c></returns>
                  public static string ToStringFast(this {{@enum.GlobalFullyQualifiedName}} value) =>
                      value switch
                      {
                          {{For(@enum.Members, x => $"{@enum.GlobalFullyQualifiedName}.{x.Key} => nameof({@enum.GlobalFullyQualifiedName}.{x.Key}),"):\n:}}
                          {{If(@enum.Flags)}}
                          _ => value.ToString(),
                          {{Else}}
                          _ => value.AsUnderlyingType().ToString(global::System.Globalization.CultureInfo.InvariantCulture),
                          {{End}}
                      };

                  /// <summary>
                  /// Returns the string representation of the <see cref="{{@enum.GlobalFullyQualifiedName}}"/> value.
                  /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                  /// </summary>
                  /// <param name="value">The value to retrieve the string value for</param>
                  /// <param name="options">The options to use when serializing the enum</param>
                  /// <returns>The string representation of the value, using the provided options.</returns>
                  {{AddOverloadResolutionPriority(@enum)}}
                  public static string ToStringFast(this {{@enum.GlobalFullyQualifiedName}} value, {{@enum.SerializationOptions}} options) =>
                  {{If(@enum.Options.HasMetadataNames)}}
                      options.UseMetadataAttributes
                          ? options.Transform switch
                          {
                              {{@enum.SerializationTransform}}.LowerInvariant => value.ToStringFastWithMetadataLowerInvariant(),
                              {{@enum.SerializationTransform}}.UpperInvariant => value.ToStringFastWithMetadataUpperInvariant(),
                              _ => value.ToStringFastWithMetadata(),
                          }
                          : options.Transform switch
                          {
                              {{@enum.SerializationTransform}}.LowerInvariant => value.ToStringFastLowerInvariant(),
                              {{@enum.SerializationTransform}}.UpperInvariant => value.ToStringFastUpperInvariant(),
                              _ => value.ToStringFast(),
                          };
                  {{Else}}
                      options.Transform switch
                      {
                          {{@enum.SerializationTransform}}.LowerInvariant => value.ToStringFastLowerInvariant(),
                          {{@enum.SerializationTransform}}.UpperInvariant => value.ToStringFastUpperInvariant(),
                          _ => value.ToStringFast(),
                      };
                  {{End}}
              }
              """);
    }

    private static Action<Code>? AddOverloadResolutionPriority(EnumDefinition @enum)
    {
        if (@enum.Options.HasOverloadResolutionPriority)
            return code => code.Append(
                // lang=c#
                """
                #if !NETESCAPADES_ENUMGENERATORS_OMIT_OVERLOAD_PRIORITY
                [global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]
                #endif
                """);
        else
            return null;
    }

    private static class Constants
    {
        public const string Version = "0.0.0";
    }
}