using Solid.Examples.NetEscapades.EnumGenerators.Models;

namespace Solid.Examples.NetEscapades.EnumGenerators;

public class EnumGeneratorTests
{
    [Fact]
    public void NoNamespace_NoRuntimeDependencies_NoOverloadResolutionPriority_NoMetadataNames()
    {
        var code = EnumGenerator.Generate(
            new EnumDefinition(
                new EnumOptions(
                    HasRuntimeDependencies: false,
                    HasOverloadResolutionPriority: false,
                    HasMetadataNames: false),
                null,
                "Colour",
                [
                    new EnumMember("Red", "Red", "1"),
                    new EnumMember("Green", "Green", "2"),
                    new EnumMember("Blue", "Blue", "3"),
                ],
                "public"));

        Assert.Equal(
            // lang=C#
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the NetEscapades.EnumGenerators source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable

            #pragma warning disable CS0612 // Ignore usages of obsolete members or enums
            #pragma warning disable CS0618 // Ignore usages of obsolete members or enums

            /// <summary>
            /// Extension methods for <see cref="global::Colour"/>
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NetEscapades.EnumGenerators", "0.0.0")]
            public static partial class Colour
            {
                /// <summary>
                /// The number of members in the enum.
                /// This is a non-distinct count of defined names.
                /// </summary>
                public const int Length = 3;

                /// <summary>
                /// Returns the string representation of the <see cref="global::Colour"/> value.
                /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                /// </summary>
                /// <param name="value">The value to retrieve the string value for</param>
                /// <returns>The string representation of the value, the same as that returned by <c>ToString()</c></returns>
                public static string ToStringFast(this global::Colour value) =>
                    value switch
                    {
                        global::Colour.Red => nameof(global::Colour.Red),
                        global::Colour.Green => nameof(global::Colour.Green),
                        global::Colour.Blue => nameof(global::Colour.Blue),
                        _ => value.AsUnderlyingType().ToString(global::System.Globalization.CultureInfo.InvariantCulture),
                    };

                /// <summary>
                /// Returns the string representation of the <see cref="global::Colour"/> value.
                /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                /// </summary>
                /// <param name="value">The value to retrieve the string value for</param>
                /// <param name="options">The options to use when serializing the enum</param>
                /// <returns>The string representation of the value, using the provided options.</returns>
                public static string ToStringFast(this global::Colour value, global::Colour.SerializationOptions options) =>
                    options.Transform switch
                    {
                        global::Colour.SerializationTransform.LowerInvariant => value.ToStringFastLowerInvariant(),
                        global::Colour.SerializationTransform.UpperInvariant => value.ToStringFastUpperInvariant(),
                        _ => value.ToStringFast(),
                    };
            }
            """.ReplaceLineEndings("\n"),
            code.ToString());
    }
    
    [Fact]
    public void WithNamespace_HasRuntimeDependencies_HasOverloadResolutionPriority_HasMetadataNames()
    {
        var code = EnumGenerator.Generate(
            new EnumDefinition(
                new EnumOptions(
                    HasRuntimeDependencies: true,
                    HasOverloadResolutionPriority: true,
                    HasMetadataNames: true),
                "Some.Namespace",
                "Colour",
                [
                    new EnumMember("Red", "Red", "1"),
                    new EnumMember("Green", "Green", "2"),
                    new EnumMember("Blue", "Blue", "3"),
                ],
                "public"));

        Assert.Equal(
            // lang=C#
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the NetEscapades.EnumGenerators source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable

            namespace Some.Namespace
            {
                #pragma warning disable CS0612 // Ignore usages of obsolete members or enums
                #pragma warning disable CS0618 // Ignore usages of obsolete members or enums
                
                /// <summary>
                /// Extension methods for <see cref="global::Some.Namespace.Colour"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("NetEscapades.EnumGenerators", "0.0.0")]
                public static partial class Colour
                {
                    /// <summary>
                    /// The number of members in the enum.
                    /// This is a non-distinct count of defined names.
                    /// </summary>
                    public const int Length = 3;
                
                    /// <summary>
                    /// Returns the string representation of the <see cref="global::Some.Namespace.Colour"/> value.
                    /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                    /// </summary>
                    /// <param name="value">The value to retrieve the string value for</param>
                    /// <returns>The string representation of the value, the same as that returned by <c>ToString()</c></returns>
                    public static string ToStringFast(this global::Some.Namespace.Colour value) =>
                        value switch
                        {
                            global::Some.Namespace.Colour.Red => nameof(global::Some.Namespace.Colour.Red),
                            global::Some.Namespace.Colour.Green => nameof(global::Some.Namespace.Colour.Green),
                            global::Some.Namespace.Colour.Blue => nameof(global::Some.Namespace.Colour.Blue),
                            _ => value.AsUnderlyingType().ToString(global::System.Globalization.CultureInfo.InvariantCulture),
                        };
                
                    /// <summary>
                    /// Returns the string representation of the <see cref="global::Some.Namespace.Colour"/> value.
                    /// Directly equivalent to calling <c>ToString()</c> on <paramref name="value"/>.
                    /// </summary>
                    /// <param name="value">The value to retrieve the string value for</param>
                    /// <param name="options">The options to use when serializing the enum</param>
                    /// <returns>The string representation of the value, using the provided options.</returns>
                    #if !NETESCAPADES_ENUMGENERATORS_OMIT_OVERLOAD_PRIORITY
                    [global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]
                    #endif
                    public static string ToStringFast(this global::Some.Namespace.Colour value, global::NetEscapades.EnumGenerators.SerializationOptions options) =>
                        options.UseMetadataAttributes
                            ? options.Transform switch
                            {
                                global::NetEscapades.EnumGenerators.SerializationTransform.LowerInvariant => value.ToStringFastWithMetadataLowerInvariant(),
                                global::NetEscapades.EnumGenerators.SerializationTransform.UpperInvariant => value.ToStringFastWithMetadataUpperInvariant(),
                                _ => value.ToStringFastWithMetadata(),
                            }
                            : options.Transform switch
                            {
                                global::NetEscapades.EnumGenerators.SerializationTransform.LowerInvariant => value.ToStringFastLowerInvariant(),
                                global::NetEscapades.EnumGenerators.SerializationTransform.UpperInvariant => value.ToStringFastUpperInvariant(),
                                _ => value.ToStringFast(),
                            };
                }
            }
            """.ReplaceLineEndings("\n"),
            code.ToString());
    }
}