using Solid.Examples.System.Text.Json.Models;

namespace Solid.Examples.System.Text.Json;

public class ContextGeneratorTests
{
    [Fact]
    public void NoNamespace_NoNested_NoInterface_NoPrimarySourceFile_NoEmitValueTypeSetterDelegate()
    {
        var code = ContextGenerator.Generate(
            new ContextDefinition(
                new ContextOptions(
                    IsPrimarySourceFile: false,
                    EmitValueTypeSetterDelegate: false),
                null,
                null,
                "SomeContext",
                null));

        Assert.Equal(
            // lang=C#
            """
            // <auto-generated/>
            
            #nullable enable annotations
            #nullable disable warnings
            
            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            public partial class SomeContext
            {
                private readonly static global::System.Text.Json.JsonSerializerOptions s_defaultOptions = new();
            
                private const global::System.Reflection.BindingFlags InstanceMemberBindingFlags =
                    global::System.Reflection.BindingFlags.Instance |
                    global::System.Reflection.BindingFlags.Public |
                    global::System.Reflection.BindingFlags.NonPublic;
            
                /// <summary>
                /// The default <see cref="global::System.Text.Json.JsonSerializerOptions"/> associated with a default <see cref="global::System.Text.Json.JsonSerializerOptions"/> instance.
                /// </summary>
                public static SomeContext Default { get; } = new SomeContext(new global::System.Text.Json.JsonSerializerOptions(s_defaultOptions));
            
                /// <summary>
                /// The source-generated options associated with this context.
                /// </summary>
                protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions { get; } = s_defaultOptions;
            
                /// <inheritdoc/>
                public SomeContext() : base(null)
                {
                }
            
                /// <inheritdoc/>
                public SomeContext(global::System.Text.Json.JsonSerializerOptions options) : base(options)
                {
                }
            }
            """.ReplaceLineEndings("\n"),
            code.ToString());
    }

    [Fact]
    public void WithNamespace_WithNested_WithInterface_PrimarySourceFile_EmitValueTypeSetterDelegate()
    {
        var code = ContextGenerator.Generate(
            new ContextDefinition(
                new ContextOptions(
                    IsPrimarySourceFile: true,
                    EmitValueTypeSetterDelegate: true),
                "Some.Namespace",
                ["First", "Second"],
                "SomeContext",
                "ISomeContext"));

        Assert.Equal(
            // lang=C#
            """
            // <auto-generated/>
            
            #nullable enable annotations
            #nullable disable warnings
            
            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618
            
            namespace Some.Namespace
            {
                public partial class First
                {
                    public partial class Second
                    {
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Some.Assembly", "0.0.0")]
                        public partial class SomeContext : ISomeContext
                        {
                            private readonly static global::System.Text.Json.JsonSerializerOptions s_defaultOptions = new();
                        
                            private const global::System.Reflection.BindingFlags InstanceMemberBindingFlags =
                                global::System.Reflection.BindingFlags.Instance |
                                global::System.Reflection.BindingFlags.Public |
                                global::System.Reflection.BindingFlags.NonPublic;
                        
                            private delegate void ValueTypeSetter<TDeclaringType, TValue>(ref TDeclaringType obj, TValue value);
                        
                            /// <summary>
                            /// The default <see cref="global::System.Text.Json.JsonSerializerOptions"/> associated with a default <see cref="global::System.Text.Json.JsonSerializerOptions"/> instance.
                            /// </summary>
                            public static SomeContext Default { get; } = new SomeContext(new global::System.Text.Json.JsonSerializerOptions(s_defaultOptions));
                        
                            /// <summary>
                            /// The source-generated options associated with this context.
                            /// </summary>
                            protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions { get; } = s_defaultOptions;
                        
                            /// <inheritdoc/>
                            public SomeContext() : base(null)
                            {
                            }
                        
                            /// <inheritdoc/>
                            public SomeContext(global::System.Text.Json.JsonSerializerOptions options) : base(options)
                            {
                            }
                        }
                    }
                }
            }
            """.ReplaceLineEndings("\n"),
            code.ToString());
    }
}