using Solid.Examples.System.Text.Json.Models;
using Solid.Templates;
using Solid.Templates.Controls;
using static Solid.Templates.Controls.Fluent;

namespace Solid.Examples.System.Text.Json;

/// <summary>
///     Demonstrates how <c>Solid.Templates</c> could have been used in <c>System.Text.Json</c>.
///     <para/>
///     The example below tries to replicate the behavior of
///     <a href="https://github.com/dotnet/runtime/blob/6bd973a541700487cb4a1891943c2a7a55e4c956/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs">
///     <c>JsonSourceGenerator.Emitter</c>
///     </a>
///     (as of commit
///     <a href="https://github.com/dotnet/runtime/commit/6bd973a541700487cb4a1891943c2a7a55e4c956">
///     <c>6bd973a</c>
///     </a>).
/// </summary>
internal static class ContextGenerator
{
    public static Code Generate(ContextDefinition context)
    {
        var code = new Code();

        code.Append(
            // lang=c#
            $$"""
            // <auto-generated/>

            #nullable enable annotations
            #nullable disable warnings

            // Suppress warnings about [Obsolete] member usage in generated code.
            #pragma warning disable CS0612, CS0618

            {{If(context.Namespace is not null)}}
            namespace {{context.Namespace}}
            {
                {{Body(context)}}
            }
            {{Else}}
            {{Body(context)}}
            {{End}}
            """);

        return code;
    }

    private static Action<Code> Body(ContextDefinition context)
    {
        return code =>
        {
            if (context.Containers?.Count > 0)
            {
                code.Append(
                    // lang=c#
                    $$"""
                      public partial class {{context.Containers[0]}}
                      {
                          {{Body(context with { Containers = context.Containers[1..] })}}
                      }
                      """);
            }
            else
            {
                Context(code, context);
            }
        };
    }

    private static void Context(Code code, ContextDefinition context)
    {
        code.Append(
            // lang=c#
            $$"""
              {{If(context.Options.IsPrimarySourceFile)}}
              [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Assembly.Name}}", "{{Assembly.Version}}")]
              {{End}}
              public partial class {{context.Name}}{{If(context.Interface is not null)}} : {{context.Interface}}{{End}}
              {
                  private readonly static {{Types.JsonSerializerOptions}} s_defaultOptions = new();

                  private const global::System.Reflection.BindingFlags InstanceMemberBindingFlags =
                      global::System.Reflection.BindingFlags.Instance |
                      global::System.Reflection.BindingFlags.Public |
                      global::System.Reflection.BindingFlags.NonPublic;
              }
              """);
    }

    private static class Types
    {
        public const string JsonSerializerOptions = "global::System.Text.Json.JsonSerializerOptions";
    }

    private static class Assembly
    {
        public const string Name = "Some.Assembly";
        public const string Version = "0.0.0";
    }
}